In [1]:
# Install & Import Libraries
import pandas as pd
import numpy as np

import os
from datetime import datetime
import warnings

In [2]:
# Set Other Configs
pd.options.display.float_format = '{:,.2f}'.format
warnings.filterwarnings(action="ignore")

In [3]:
# Set Path Configs
ROOT_PATH = os.getcwd()
DATA_PATH = os.path.join(ROOT_PATH, 'data')
IMAGE_DATA_PATH = os.path.join(DATA_PATH, 'images')
RAW_DATA_PATH = os.path.join(DATA_PATH, 'input')
PROCESSED_DATA_PATH = os.path.join(DATA_PATH, 'processed')

### Read Movies Data

In [4]:
# df_movies_data = pd.read_csv(os.path.join(RAW_DATA_PATH, "MovieGenre.csv"), encoding='latin-1')
df_movies_data = pd.read_csv(os.path.join(RAW_DATA_PATH, "MovieGenre.csv.gz"))
df_movies_data

,Unnamed: 0,imdbId,Imdb Link,Title,IMDB Score,Genre,Poster
0,0,114709,http://www.imdb.com/title/tt114709,Toy Story (1995),8.30,Animation|Adventure|Comedy,https://images-na.ssl-images-amazon.com/images...
1,1,113497,http://www.imdb.com/title/tt113497,Jumanji (1995),6.90,Action|Adventure|Family,https://images-na.ssl-images-amazon.com/images...
2,2,113228,http://www.imdb.com/title/tt113228,Grumpier Old Men (1995),6.60,Comedy|Romance,https://images-na.ssl-images-amazon.com/images...
3,3,114885,http://www.imdb.com/title/tt114885,Waiting to Exhale (1995),5.70,Comedy|Drama|Romance,https://images-na.ssl-images-amazon.com/images...
4,4,113041,http://www.imdb.com/title/tt113041,Father of the Bride Part II (1995),5.90,Comedy|Family|Romance,https://images-na.ssl-images-amazon.com/images...
...,...,...,...,...,...,...,...
40103,40103,83168,http://www.imdb.com/title/tt83168,Tanya's Island (1980),4.30,Drama,https://images-na.ssl-images-amazon.com/images...
40104,40104,82875,http://www.imdb.com/title/tt82875,Pacific Banana (1981),4.70,Comedy,https://images-na.ssl-images-amazon.com/images...
40105,40105,815258,http://www.imdb.com/title/tt815258,Werewolf in a Womens Prison (2006),4.50,Horror,https://images-na.ssl-images-amazon.com/images...
40106,40106,79142,http://www.imdb.com/title/tt79142,Xiao zi ming da (1979),6.50,Action|Comedy,https://images-na.ssl-images-amazon.com/images...
40107,40107,70710,http://www.imdb.com/title/tt70710,Snatched (1973),6.50,Crime|Drama|Thriller,NaN

In [5]:
df_movies_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40108 entries, 0 to 40107
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  40108 non-null  int64
 1   imdbId      40108 non-null  int64
 2   Imdb Link   40108 non-null  object
 3   Title       40108 non-null  object
 4   IMDB Score  40060 non-null  float64
 5   Genre       39963 non-null  object
 6   Poster      39383 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 2.1+ MB

In [6]:
df_movies_data['imdbId'] = df_movies_data['imdbId'].astype('int32')
df_movies_data['imdbId'].dtype

dtype('int32')

In [7]:
df_movies_data.sort_values(by=['imdbId'], ascending=True, inplace=True)

In [8]:
duplicated_movie_list = df_movies_data[df_movies_data['imdbId'].duplicated()]['imdbId'].to_list()
print("Duplicate Movies Count:", len(duplicated_movie_list))

Duplicate Movies Count: 593

In [9]:
df_movies_data[(df_movies_data['imdbId'].isin(duplicated_movie_list))].sort_values(by=['imdbId'], ascending=True)

,Unnamed: 0,imdbId,Imdb Link,Title,IMDB Score,Genre,Poster
12409,12409,11358,http://www.imdb.com/title/tt11358,Just Pals (1920),6.60,Comedy|Drama|Western,https://images-na.ssl-images-amazon.com/images...
13003,13003,11358,http://www.imdb.com/title/tt11358,Just Pals (1920),6.60,Comedy|Drama|Western,https://images-na.ssl-images-amazon.com/images...
12748,12748,11439,http://www.imdb.com/title/tt11439,The Mark of Zorro (1920),7.30,Adventure|Romance|Western,https://images-na.ssl-images-amazon.com/images...
13342,13342,11439,http://www.imdb.com/title/tt11439,The Mark of Zorro (1920),7.30,Adventure|Romance|Western,https://images-na.ssl-images-amazon.com/images...
13344,13344,12752,http://www.imdb.com/title/tt12752,The Three Musketeers (1921),7.00,Action|Adventure|Romance,https://images-na.ssl-images-amazon.com/images...
...,...,...,...,...,...,...,...
12707,12707,1151309,http://www.imdb.com/title/tt1151309,Bigger Stronger Faster* (2008),7.60,Documentary|Sport,https://images-na.ssl-images-amazon.com/images...
12521,12521,1166827,http://www.imdb.com/title/tt1166827,Zeitgeist (2007),8.20,Documentary|History,https://images-na.ssl-images-amazon.com/images...
13115,13115,1166827,http://www.imdb.com/title/tt1166827,Zeitgeist (2007),8.20,Documentary|History,https://images-na.ssl-images-amazon.com/images...
13304,13304,1219671,http://www.imdb.com/title/tt1219671,Allan Quatermain and the Temple of Skulls (2008),2.60,Action|Adventure|Romance,https://images-na.ssl-images-amazon.com/images...
12710,12710,1219671,http://www.imdb.com/title/tt1219671,Allan Quatermain and the Temple of Skulls (2008),2.60,Action|Adventure|Romance,https://images-na.ssl-images-amazon.com/images...

In [10]:
df_movies_data.drop_duplicates(keep='first', inplace=True)

### Read Image List

In [11]:
image_list = os.listdir(IMAGE_DATA_PATH)

In [12]:
df_images_data = pd.DataFrame(image_list, columns=['ImgName'])

df_images_data['ImgId'] = df_images_data['ImgName'].apply(lambda x: x.split('.')[0])
# df_images_data['ImgId'] = df_images_data['ImgName'].str.split('.', expand=True)[0]

df_images_data

       ImgName  ImgId
0    10040.jpg  10040
1    10057.jpg  10057
2    10071.jpg  10071
3    10155.jpg  10155
4    10195.jpg  10195
..         ...    ...
992   9899.jpg   9899
993   9932.jpg   9932
994   9937.jpg   9937
995   9968.jpg   9968
996   9976.jpg   9976

[997 rows x 2 columns]

In [13]:
df_images_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 997 entries, 0 to 996
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   ImgName  997 non-null    object
 1   ImgId    997 non-null    object
dtypes: object(2)
memory usage: 15.7+ KB

In [14]:
df_images_data['ImgId'] = df_images_data['ImgId'].astype('int32')
df_images_data['ImgId'].dtype

dtype('int32')

In [15]:
df_movies_data.shape, df_images_data.shape

((40108, 7), (997, 2))

In [16]:
df_movies_data['imdbId'].nunique(), df_images_data['ImgId'].nunique()

(39515, 997)

In [17]:
df_master_data = pd.merge(left=df_movies_data, right=df_images_data, how='inner', left_on=['imdbId'], right_on=['ImgId']).reset_index(drop=True)

In [18]:
df_master_data.columns = df_master_data.columns.str.replace(' ', '')
df_master_data.rename(columns={'imdbId':'ImdbId'}, inplace=True)
df_master_data

,Unnamed:0,ImdbId,ImdbLink,Title,IMDBScore,Genre,Poster,ImgName,ImgId
0,18428,2461,http://www.imdb.com/title/tt2461,Richard III (1912),5.70,Drama,https://images-na.ssl-images-amazon.com/images...,2461.jpg,2461
1,27778,2544,http://www.imdb.com/title/tt2544,TrÃŒ_dgÃŒÂ´rdsmÃŒ_staren (1912),6.40,Drama,https://images-na.ssl-images-amazon.com/images...,2544.jpg,2544
2,37540,2795,http://www.imdb.com/title/tt2795,Death's Marathon (1913),6.20,Short|Drama|Romance,https://images-na.ssl-images-amazon.com/images...,2795.jpg,2795
3,21289,2844,http://www.imdb.com/title/tt2844,FantÃŒÂ«mas: In the Shadow of the Guillotine (1913),6.90,Crime|Drama,https://images-na.ssl-images-amazon.com/images...,2844.jpg,2844
4,37539,2985,http://www.imdb.com/title/tt2985,The House of Darkness (1913),6.10,Short|Drama,https://images-na.ssl-images-amazon.com/images...,2985.jpg,2985
...,...,...,...,...,...,...,...,...,...
1013,10401,25580,http://www.imdb.com/title/tt25580,Now and Forever (1934),6.60,Drama|Romance,https://images-na.ssl-images-amazon.com/images...,25580.jpg,25580
1014,942,25586,http://www.imdb.com/title/tt25586,Of Human Bondage (1934),7.30,Drama|Romance,https://images-na.ssl-images-amazon.com/images...,25586.jpg,25586
1015,18684,25590,http://www.imdb.com/title/tt25590,The Old Fashioned Way (1934),7.60,Comedy,https://images-na.ssl-images-amazon.com/images...,25590.jpg,25590
1016,27131,25601,http://www.imdb.com/title/tt25601,One Night of Love (1934),6.00,Music|Romance,https://images-na.ssl-images-amazon.com/images...,25601.jpg,25601
1017,15822,25607,http://www.imdb.com/title/tt25607,Operator 13 (1934),7.90,Drama|History|Romance,https://images-na.ssl-images-amazon.com/images...,25607.jpg,25607

In [19]:
df_master_data = df_master_data.join(df_master_data['Genre'].str.split('|', expand=True))
df_master_data.rename(columns={0:'Genre1', 1:'Genre2', 2:'Genre3'}, inplace=True)
df_master_data

,Unnamed:0,ImdbId,ImdbLink,Title,IMDBScore,Genre,Poster,ImgName,ImgId,Genre1,Genre2,Genre3
0,18428,2461,http://www.imdb.com/title/tt2461,Richard III (1912),5.70,Drama,https://images-na.ssl-images-amazon.com/images...,2461.jpg,2461,Drama,None,None
1,27778,2544,http://www.imdb.com/title/tt2544,TrÃŒ_dgÃŒÂ´rdsmÃŒ_staren (1912),6.40,Drama,https://images-na.ssl-images-amazon.com/images...,2544.jpg,2544,Drama,None,None
2,37540,2795,http://www.imdb.com/title/tt2795,Death's Marathon (1913),6.20,Short|Drama|Romance,https://images-na.ssl-images-amazon.com/images...,2795.jpg,2795,Short,Drama,Romance
3,21289,2844,http://www.imdb.com/title/tt2844,FantÃŒÂ«mas: In the Shadow of the Guillotine (1913),6.90,Crime|Drama,https://images-na.ssl-images-amazon.com/images...,2844.jpg,2844,Crime,Drama,None
4,37539,2985,http://www.imdb.com/title/tt2985,The House of Darkness (1913),6.10,Short|Drama,https://images-na.ssl-images-amazon.com/images...,2985.jpg,2985,Short,Drama,None
...,...,...,...,...,...,...,...,...,...,...,...,...
1013,10401,25580,http://www.imdb.com/title/tt25580,Now and Forever (1934),6.60,Drama|Romance,https://images-na.ssl-images-amazon.com/images...,25580.jpg,25580,Drama,Romance,None
1014,942,25586,http://www.imdb.com/title/tt25586,Of Human Bondage (1934),7.30,Drama|Romance,https://images-na.ssl-images-amazon.com/images...,25586.jpg,25586,Drama,Romance,None
1015,18684,25590,http://www.imdb.com/title/tt25590,The Old Fashioned Way (1934),7.60,Comedy,https://images-na.ssl-images-amazon.com/images...,25590.jpg,25590,Comedy,None,None
1016,27131,25601,http://www.imdb.com/title/tt25601,One Night of Love (1934),6.00,Music|Romance,https://images-na.ssl-images-amazon.com/images...,25601.jpg,25601,Music,Romance,None
1017,15822,25607,http://www.imdb.com/title/tt25607,Operator 13 (1934),7.90,Drama|History|Romance,https://images-na.ssl-images-amazon.com/images...,25607.jpg,25607,Drama,History,Romance

In [20]:
df_master_data_genre_grpby = df_master_data.groupby(by=['Genre1'], as_index=False).agg(Cnt=('ImdbId','count')).sort_values(by=['Cnt'], ascending=False)
df_master_data_genre_grpby['CntRatio'] = df_master_data_genre_grpby['Cnt'] / df_master_data.shape[0] * 100
df_master_data_genre_grpby['CumSum'] = df_master_data_genre_grpby['Cnt'].cumsum()
df_master_data_genre_grpby['CumRatio'] = df_master_data_genre_grpby['CumSum'] / df_master_data.shape[0] * 100
df_master_data_genre_grpby

         Genre1  Cnt  CntRatio  CumSum  CumRatio
7         Drama  358     35.17     358     35.17
4        Comedy  271     26.62     629     61.79
5         Crime   86      8.45     715     70.24
16        Short   62      6.09     777     76.33
1     Adventure   56      5.50     833     81.83
0        Action   40      3.93     873     85.76
2     Animation   23      2.26     896     88.02
3     Biography   21      2.06     917     90.08
6   Documentary   17      1.67     934     91.75
15      Romance   17      1.67     951     93.42
11       Horror   13      1.28     964     94.70
14      Mystery   12      1.18     976     95.87
9       Fantasy   12      1.18     988     97.05
18      Western   11      1.08     999     98.13
13      Musical    8      0.79    1007     98.92
10      History    3      0.29    1010     99.21
8        Family    3      0.29    1013     99.51
17          War    3      0.29    1016     99.80
12        Music    2      0.20    1018    100.00

In [21]:
selected_genre_list = df_master_data_genre_grpby['Genre1'].to_list()
selected_genre_list = selected_genre_list[0:5]
selected_genre_list

['Drama', 'Comedy', 'Crime', 'Short', 'Adventure']

In [22]:
df_master_data = df_master_data[(df_master_data['Genre1'].isin(selected_genre_list))][['ImgId', 'ImgName', 'Title', 'Genre1', 'Genre2', 'Genre3', 'IMDBScore', 'ImdbLink', 'Poster']]
df_master_data

,ImgId,ImgName,Title,Genre1,Genre2,Genre3,IMDBScore,ImdbLink,Poster
0,2461,2461.jpg,Richard III (1912),Drama,None,None,5.70,http://www.imdb.com/title/tt2461,https://images-na.ssl-images-amazon.com/images...
1,2544,2544.jpg,TrÃŒ_dgÃŒÂ´rdsmÃŒ_staren (1912),Drama,None,None,6.40,http://www.imdb.com/title/tt2544,https://images-na.ssl-images-amazon.com/images...
2,2795,2795.jpg,Death's Marathon (1913),Short,Drama,Romance,6.20,http://www.imdb.com/title/tt2795,https://images-na.ssl-images-amazon.com/images...
3,2844,2844.jpg,FantÃŒÂ«mas: In the Shadow of the Guillotine (1913),Crime,Drama,None,6.90,http://www.imdb.com/title/tt2844,https://images-na.ssl-images-amazon.com/images...
4,2985,2985.jpg,The House of Darkness (1913),Short,Drama,None,6.10,http://www.imdb.com/title/tt2985,https://images-na.ssl-images-amazon.com/images...
...,...,...,...,...,...,...,...,...,...
1012,25555,25555.jpg,Nana (1934),Drama,None,None,6.10,http://www.imdb.com/title/tt25555,https://images-na.ssl-images-amazon.com/images...
1013,25580,25580.jpg,Now and Forever (1934),Drama,Romance,None,6.60,http://www.imdb.com/title/tt25580,https://images-na.ssl-images-amazon.com/images...
1014,25586,25586.jpg,Of Human Bondage (1934),Drama,Romance,None,7.30,http://www.imdb.com/title/tt25586,https://images-na.ssl-images-amazon.com/images...
1015,25590,25590.jpg,The Old Fashioned Way (1934),Comedy,None,None,7.60,http://www.imdb.com/title/tt25590,https://images-na.ssl-images-amazon.com/images...
1017,25607,25607.jpg,Operator 13 (1934),Drama,History,Romance,7.90,http://www.imdb.com/title/tt25607,https://images-na.ssl-images-amazon.com/images...

In [24]:
df_master_data.to_csv(os.path.join(PROCESSED_DATA_PATH, "MasterData.csv.gz"), compression='gzip', index=False)